/* 게시판 */
CREATE TABLE BOARD (
  BD_NO VARCHAR2(50) NOT NULL, /* 게시번호 */
  BD_TITLE VARCHAR2(90) NOT NULL, /* 제목 */
  BD_CONTENT CLOB NOT NULL, /* 내용 */
  BD_VIEW VARCHAR2(10) NOT NULL, /* 조회수 */
  BD_DATE DATE NOT NULL, /* 작성일 */
  BD_FILE BLOB, /* 첨부파일 */
  BD_MEMID VARCHAR2(14) NOT NULL, /* 아이디 */
  BD_MEMPASS VARCHAR2(255) NOT NULL, /* 비밀번호 */
  BD_MEMNICK VARCHAR2(30) /* 별명 */
);

COMMENT ON TABLE BOARD IS '게시판';

COMMENT ON COLUMN BOARD.BD_NO IS '게시번호';

COMMENT ON COLUMN BOARD.BD_TITLE IS '제목';

COMMENT ON COLUMN BOARD.BD_CONTENT IS '내용';

COMMENT ON COLUMN BOARD.BD_VIEW IS '조회수';

COMMENT ON COLUMN BOARD.BD_DATE IS '작성일';

COMMENT ON COLUMN BOARD.BD_FILE IS '첨부파일';

COMMENT ON COLUMN BOARD.BD_MEMID IS '아이디';

COMMENT ON COLUMN BOARD.BD_MEMPASS IS '비밀번호';

COMMENT ON COLUMN BOARD.BD_MEMNICK IS '별명';

CREATE UNIQUE INDEX PK_BOARD
  ON BOARD (
    BD_NO ASC
  );

ALTER TABLE BOARD
  ADD
  CONSTRAINT PK_BOARD
  PRIMARY KEY (
    BD_NO
  );

/* 회원 */
CREATE TABLE MEMBER (
  MEM_ID VARCHAR2(14) NOT NULL, /* 아이디 */
  MEM_PASS VARCHAR2(255) NOT NULL, /* 비밀번호 */
  MEM_NAME VARCHAR2(50) NOT NULL, /* 이름 */
  MEM_NICK VARCHAR2(30), /* 별명 */
  MEM_BIRTH DATE NOT NULL, /* 생년월일 */
  MEM_HP VARCHAR2(13) NOT NULL, /* 핸드폰 */
  MEM_EMAIL VARCHAR2(40) NOT NULL, /* 이메일 */
  MEM_ZIP VARCHAR2(5) NOT NULL, /* 우편번호 */
  MEM_ADDR1 VARCHAR2(255) NOT NULL, /* 도로명 */
  MEM_ADDR2 VARCHAR2(255) NOT NULL, /* 상세주소 */
  MEM_PROFILE VARCHAR2(255) /* 사진 */
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.MEM_ID IS '아이디';

COMMENT ON COLUMN MEMBER.MEM_PASS IS '비밀번호';

COMMENT ON COLUMN MEMBER.MEM_NAME IS '이름';

COMMENT ON COLUMN MEMBER.MEM_NICK IS '별명';

COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '생년월일';

COMMENT ON COLUMN MEMBER.MEM_HP IS '핸드폰';

COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.MEM_ZIP IS '우편번호';

COMMENT ON COLUMN MEMBER.MEM_ADDR1 IS '도로명';

COMMENT ON COLUMN MEMBER.MEM_ADDR2 IS '상세주소';

COMMENT ON COLUMN MEMBER.MEM_PROFILE IS '사진';

CREATE UNIQUE INDEX PK_MEMBER
  ON MEMBER (
    MEM_ID ASC
  );

ALTER TABLE MEMBER
  ADD
  CONSTRAINT PK_MEMBER
  PRIMARY KEY (
    MEM_ID
  );

ALTER TABLE BOARD
  ADD
  CONSTRAINT FK_MEMBER_TO_BOARD
  FOREIGN KEY (
    BD_MEMID
  )
  REFERENCES MEMBER (
    MEM_ID
  );

select * from BOARD;
select * from MEMBER;

commit ;
