CREATE TABLE BOARD.BOARD
(
    NO VARCHAR2(50) PRIMARY KEY NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    USE VARCHAR2(1) NOT NULL,
    CREATOR VARCHAR2(14),
    RDATE DATE NOT NULL,
    CONSTRAINT FK_MEMBER_TO_BOARD FOREIGN KEY (CREATOR) REFERENCES BOARD.MEMBER (ID)
);
COMMENT ON COLUMN BOARD.BOARD.NO IS '게시판번호';
COMMENT ON COLUMN BOARD.BOARD.NAME IS '게시판이름';
COMMENT ON COLUMN BOARD.BOARD.USE IS '게시판사용여부';
COMMENT ON COLUMN BOARD.BOARD.CREATOR IS '게시판등록자';
COMMENT ON COLUMN BOARD.BOARD.RDATE IS '게시판등록일';
INSERT INTO BOARD.BOARD (NO, NAME, USE, CREATOR, RDATE) VALUES ('BD1', 'Q&A 게시판', 'Y', 'brown', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));