CREATE TABLE BOARD.COMMENTS
(
    NO VARCHAR2(50) PRIMARY KEY NOT NULL,
    POSTNO VARCHAR2(50),
    CONTENT VARCHAR2(500) NOT NULL,
    WRITER VARCHAR2(14),
    RDATE DATE,
    CONSTRAINT FK_POST_TO_COMMENTS FOREIGN KEY (POSTNO) REFERENCES BOARD.POST (NO) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_TO_COMMENTS FOREIGN KEY (WRITER) REFERENCES BOARD.MEMBER (ID)
);
COMMENT ON COLUMN BOARD.COMMENTS.NO IS '댓글번호';
COMMENT ON COLUMN BOARD.COMMENTS.POSTNO IS '게시글번호';
COMMENT ON COLUMN BOARD.COMMENTS.CONTENT IS '댓글내용';
COMMENT ON COLUMN BOARD.COMMENTS.WRITER IS '댓글작성자';
COMMENT ON COLUMN BOARD.COMMENTS.RDATE IS '댓글작성일시';
INSERT INTO BOARD.COMMENTS (NO, POSTNO, CONTENT, WRITER, RDATE) VALUES ('CMT1', 'PT11', '첫번째 댓글', 'brown', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));