CREATE TABLE BOARD.POST
(
    NO VARCHAR2(50) PRIMARY KEY NOT NULL,
    TITLE VARCHAR2(90) NOT NULL,
    CONTENT CLOB,
    RDATE DATE,
    WRITER VARCHAR2(14),
    BOARDNO VARCHAR2(50),
    RECURSION VARCHAR2(50),
    GROUPNO VARCHAR2(50),
    CONSTRAINT FK_MEMBER_TO_POST FOREIGN KEY (WRITER) REFERENCES BOARD.MEMBER (ID),
    CONSTRAINT FK_BOARD_TO_POST FOREIGN KEY (BOARDNO) REFERENCES BOARD.BOARD (NO) ON DELETE CASCADE,
    CONSTRAINT FK_POST_TO_POST FOREIGN KEY (RECURSION) REFERENCES BOARD.POST (NO)
);
COMMENT ON COLUMN BOARD.POST.NO IS '게시글번호';
COMMENT ON COLUMN BOARD.POST.TITLE IS '제목';
COMMENT ON COLUMN BOARD.POST.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.POST.RDATE IS '작성일시';
COMMENT ON COLUMN BOARD.POST.WRITER IS '작성자 ID';
COMMENT ON COLUMN BOARD.POST.BOARDNO IS '게시판번호';
COMMENT ON COLUMN BOARD.POST.RECURSION IS '부모게시글번호';
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('33', 'test122', '<p> test</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '33');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('34', 'íì¤í¸ë¥¼ ìí ê¸ ìëë¤.', '<p>ë§ìê»í´ì£¼ì¸ì</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '34');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('35', '테스트 중입니다.', '<p>한글이 깨지네?!</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '35');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('36', '화면 넘어가 라', '<p>123</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '36');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('37', '첨부파일 도전', '<p>111</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '37');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('38', '맨날 터져!', '<p>ㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '38');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('11', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, '1');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('12', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, '2');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('39', '페이징 테스트', '<p>ㄴㅇㄹㅇㄹㄴㅇ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '39');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('13', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, '3');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('15', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'james', 'BD1', '11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('16', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'moon', 'BD1', '12', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('17', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'moon', 'BD1', '13', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('40', 'ㄴㄹㄴ', '<p>ㅇㄹㅇㄹㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '40');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('41', '1', '<p>1</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '41');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('43', '1', '<p>ㄴㅇㄹㅇㄴㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '43');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('44', 'ㄴㅇㄹ', '<p>ㅇㄹㅇ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '44');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('45', 'ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ', '<p>ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '45');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('46', 'ㅇㄹㅇㄹ', '<p>ㅇㄴㄹㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '46');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('47', '파일전송 테스트', '<p>ㄴㅇㄹㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '47');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('48', '되징', '<p>ㄷㄹㅇㄴㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '48');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('18', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'cony', 'BD1', '11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('19', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'xxxx1', 'BD1', '13', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('20', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'xxxx2', 'BD1', '11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('21', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', '12', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('22', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', '20', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('23', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', '19', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('24', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', '19', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('31', 'test1', '<p> test</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '15');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('32', 'test122', '<p> test</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '32');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('49', '화면 변경', '<p>ㄴㅇㄹㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '49');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('50', '화면아 오라', '<p>ㅇㄹㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '50');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('51', '메인으로 가자', '<p>ㅇㄹㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '51');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('52', '그림 넣어 볼까?', '<p><img src="/upload/67020659-2e03-46d8-ab5f-19e3f1ade90f.png&#10;" title="20180703_214624.png"><br style="clear:both;">&nbsp;</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '52');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('53', '첨부해줭', '<p>ㅇㄹㅇ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '53');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('54', '첨부하자', '<p>가자!</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '54');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('55', 'sdf', '<p>sdfd</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '55');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('56', 'ㄴㅇㄹ', '<p>ㅇㄹㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '56');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('57', 'ㄴㅇㄹㄴㅇ', '<p>ㄹㅇㄹㅇ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '57');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('58', 'ㄴㅇㄹ', '<p>ㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '58');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('59', 'ㄴㅇㄹ', '<p>ㅇㄴㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '59');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('60', 'ㄴㅇㄹ', '<p>ㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '60');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('61', 'ㄴㅇㄹ', '<p>ㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '61');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('62', 'ㅅㄷㅅ', '<p>ㄴㅇㄹㄴㅇㄹ</p>', TO_DATE('2018-10-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, '62');