CREATE TABLE BOARD.ATTACHMENT
(
    NO VARCHAR2(50) PRIMARY KEY NOT NULL,
    POSTNO VARCHAR2(50),
    ATT BLOB,
    CONSTRAINT FK_POST_TO_ATTACHMENT FOREIGN KEY (POSTNO) REFERENCES BOARD.POST (NO) ON DELETE CASCADE
);
COMMENT ON COLUMN BOARD.ATTACHMENT.NO IS '첨부파일번호';
COMMENT ON COLUMN BOARD.ATTACHMENT.POSTNO IS '게시글번호';
COMMENT ON COLUMN BOARD.ATTACHMENT.ATT IS '첨부파일';
INSERT INTO BOARD.ATTACHMENT (NO, POSTNO, ATT) VALUES ('8', '60', null);
INSERT INTO BOARD.ATTACHMENT (NO, POSTNO, ATT) VALUES ('11', '60', null);
INSERT INTO BOARD.ATTACHMENT (NO, POSTNO, ATT) VALUES ('10', '62', null);
INSERT INTO BOARD.ATTACHMENT (NO, POSTNO, ATT) VALUES ('12', '61', null);
INSERT INTO BOARD.ATTACHMENT (NO, POSTNO, ATT) VALUES ('13', '60', null);