CREATE TABLE BOARD.POST
(
    NO VARCHAR2(50) PRIMARY KEY NOT NULL,
    TITLE VARCHAR2(90) NOT NULL,
    CONTENT CLOB,
    RDATE DATE,
    WRITER VARCHAR2(14),
    BOARDNO VARCHAR2(50),
    RECURSION VARCHAR2(50),
    GROUPNO VARCHAR2(50),
    CONSTRAINT FK_MEMBER_TO_POST FOREIGN KEY (WRITER) REFERENCES BOARD.MEMBER (ID),
    CONSTRAINT FK_BOARD_TO_POST FOREIGN KEY (BOARDNO) REFERENCES BOARD.BOARD (NO) ON DELETE CASCADE,
    CONSTRAINT FK_POST_TO_POST FOREIGN KEY (RECURSION) REFERENCES BOARD.POST (NO)
);
COMMENT ON COLUMN BOARD.POST.NO IS '게시글번호';
COMMENT ON COLUMN BOARD.POST.TITLE IS '제목';
COMMENT ON COLUMN BOARD.POST.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.POST.RDATE IS '작성일시';
COMMENT ON COLUMN BOARD.POST.WRITER IS '작성자 ID';
COMMENT ON COLUMN BOARD.POST.BOARDNO IS '게시판번호';
COMMENT ON COLUMN BOARD.POST.RECURSION IS '부모게시글번호';
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT11', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, 'PTG1');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT12', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, 'PTG2');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT13', '제목은 지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sally', 'BD1', null, 'PTG3');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT15', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'james', 'BD1', 'PT11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT16', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'moon', 'BD1', 'PT12', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT17', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'moon', 'BD1', 'PT13', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT18', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'cony', 'BD1', 'PT11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT19', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'xxxx1', 'BD1', 'PT13', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT20', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'xxxx2', 'BD1', 'PT11', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT21', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', 'PT12', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT22', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', 'PT20', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT23', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', 'PT19', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('PT24', '지금 달려갑니다.', '이렇게 우리는 만났습니다.', TO_DATE('2018-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'brown', 'BD1', 'PT19', null);
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('test1', 'PT29', 'test1', TO_DATE('2018-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, 'test1');
INSERT INTO BOARD.POST (NO, TITLE, CONTENT, RDATE, WRITER, BOARDNO, RECURSION, GROUPNO) VALUES ('test EditPost', 'PT30', 'test1', TO_DATE('2018-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 'BD1', null, 'test1');